training:
  max_steps: 100000
  grad_agg_freq: 1
  rec_results_freq: 1000
  rec_validation_freq: 1000
  rec_inference_freq: ${training.rec_results_freq}
  rec_monitor_freq: ${training.rec_results_freq}
  rec_constraint_freq: ${training.rec_results_freq}
  save_network_freq: 1000
  print_stats_freq: 100
  summary_freq: 1000
  grad_clip_max_norm: 0.5
  monitor_grad_clip: true
  ntk:
    use_ntk: false
    save_name: null
    run_freq: 1000
amp:
  enabled: false
  mode: per_order_scaler
  dtype: float16
  autocast_activation: false
  autocast_firstlayer: false
  default_max_scale_log2: 0
  custom_max_scales_log2: {}
graph:
  func_arch: false
  func_arch_allow_partial_hessian: true
stop_criterion:
  metric: null
  min_delta: null
  patience: 50000
  mode: min
  freq: 1000
  strict: false
profiler:
  profile: false
  start_step: 0
  end_step: 100
  name: nvtx
network_dir: /content/PhysicsNemo_DeepONet/Darcy_DeepONet/outputs
initialization_network_dir: ''
save_filetypes: np
summary_histograms: 'off'
jit: true
jit_use_nvfuser: true
jit_arch_mode: only_activation
jit_autograd_nodes: false
cuda_graphs: true
cuda_graph_warmup: 20
find_unused_parameters: false
broadcast_buffers: false
device: ''
debug: false
run_mode: train
arch:
  branch:
    arch_type: pix2pix
    input_keys:
    - coeff
    output_keys:
    - branch
    detach_keys: ???
    scaling: null
    dimension: 2
    conv_layer_size: 32
    n_downsampling: 3
    n_blocks: 3
    scaling_factor: 1
    batch_norm: true
    padding_type: reflect
    activation_fn: relu
  trunk:
    arch_type: fourier
    input_keys:
    - x
    - 'y'
    output_keys:
    - trunk
    - 256
    detach_keys: ???
    scaling: null
    frequencies: ('axis', [0, 1, 2, 3, 4])
    frequencies_params: ('axis', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    activation_fn: silu
    layer_size: 128
    nr_layers: 4
    skip_connections: false
    weight_norm: true
    adaptive_activations: false
  deeponet:
    arch_type: deeponet
    input_keys: ???
    output_keys: sol
    detach_keys: ???
    scaling: null
    trunk_dim: null
    branch_dim: 1024
models: ???
loss:
  _target_: physicsnemo.sym.loss.aggregator.Sum
  weights: null
optimizer:
  _params_:
    compute_gradients: adam_compute_gradients
    apply_gradients: adam_apply_gradients
  _target_: torch.optim.Adam
  lr: 0.001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.0
  amsgrad: false
scheduler:
  _target_: custom
  _name_: tf.ExponentialLR
  decay_rate: 0.9
  decay_steps: 2000
batch_size:
  train: 1000
custom: ???
